#!/usr/bin/env bash

first_array=(
  biryani
  korma
  chicken-tikka
)

echo "$first_array"

declare -p first_array

second_array=(${first_array[@]})
second_array+=(foods)

for item in ${second_array[@]}; do
  echo "$item"
done

echo
echo
echo

array=(foo bar baz)

for item in "${array[*]}"; do
  echo "item is: $item"
done

for item in "${array[@]}"; do
  echo "item is: $item"
done
