#!/usr/bin/env bash

if [[ -n $2 ]]; then
  dir=$2
else
  dir="."
fi

if [[ -n $1 ]]; then
  format=$1
else
  echo "Format not specified"
  exit 1
fi

count=$(find "$dir" -type f -name "*.$format" | wc -l)
echo "=====$format counter====="
echo "$format files: $count"
