#!/usr/bin/env bash

if [[ -n "$1" ]]; then
  script="$1"
else
  read -p 'Enter Script Name: ' script
fi

if [[ -f "$script" ]]; then
  echo "ERROR: a file with this name already exists."
  exit 1
fi

touch "$script"
chmod +x "$script"
echo "#!/usr/bin/env bash" >"$script"
