#!/usr/bin/env bash

loading() {
  echo -ne "\r Loading"
  sleep 0.25
  echo -ne "\r Loading"
  sleep 0.25
  echo -ne "\r Loading"
  sleep 0.25
  echo -ne "\r Loading"
  sleep 0.25
  echo -ne "\r Loading"
  sleep 0.25
  echo -ne "\r Loading"
  echo -ne "\r\033[2K"
}

sff=" Site Folder Files "
gs=" Git Status "
lc="󰜘 Last Commit "

for dev in "$@"; do
  case "$dev" in

  "-site")
    loading
    printf "%${COLUMNS}s" | tr ' ' '-'
    echo "$sff"
    ls ~/anom/
    printf "%${COLUMNS}s" | tr ' ' '-'
    echo "$gs"
    git -C ~/anom status
    echo
    echo "$lc"
    git -C ~/anom log --oneline -1
    printf "%${COLUMNS}s" | tr ' ' '-'
    echo "TIP: cd to $(pwd)"
    printf "%${COLUMNS}s" | tr ' ' '-'
    ;;

  "-learn")
    loading
    printf "%${COLUMNS}s" | tr ' ' '-'
    echo "$sff"
    ls ~/learning/
    printf "%${COLUMNS}s" | tr ' ' '-'
    echo "$gs"
    git -C ~/learning/ status
    echo
    echo "$lc"
    git -C ~/learning/ log --oneline -1
    printf "%${COLUMNS}s" | tr ' ' '-'
    echo "TIP: cd to $(cd learning/ | pwd) "
    printf "%${COLUMNS}s" | tr ' ' '-'
    ;;

  esac
done
