#!/usr/bin/env bash

loading() {
    echo -ne "\r Loading"
    sleep 0.5
    echo -ne "\r Loading"
    sleep 0.5
    echo -ne "\r Loading"
    sleep 0.5
    echo -ne "\r Loading"
    sleep 0.5
    echo -ne "\r Loading"
    sleep 0.5
    echo -ne "\r\033[2K Loading"

    printf "\nYay Loading works"
  }

loading
