#!/usr/bin/env bash

hello() {
  local s=$1
  echo "Hello $s!"
}

goodbye() {
  local s=$1
  echo "Goodbye $s!"
}

if [[ $# == 0 ]]; then
  echo "Didnt anyone name you?"
fi

for name in "$@"; do
  if [[ $name == a* ]]; then
    hello "$name"
  elif [[ $name == u* ]]; then
    hello "$name"
  else
    goodbye "$name"
  fi
done
