#!/usr/bin/env bash

if [[ -n $1 ]]; then
  name=$1
else
  read -p 'Enter your name: ' name
fi

# if [[ -n $2 ]]; then
#   food=$2
# else
#   read -p 'Your fav food is: ' food
# fi

# echo "Hello $name! Your fav food is $food"
echo "Hello $name!"
